### ISSUE TITLE
Validate is not implmented for Hashmap

### ISSUE THREAD

**Issue by nickjknight** [yassun4dev/serde_valid#7]
I want to use this library to validate a field that is inside a hashmap, but validate is not implemented for std::collections::HashMap.

Suggested fix would be to do the same as you currently do for Vec<T>, and just iterate through the values of Hashmap (the V in HashMap<K, V>), and call validate() on those.

**Comment by yassun4dev** [comment]
@nickjknight 

I fiexed [hashmap key type](https://github.com/yassun4dev/serde_valid/commit/63ed216068c7513f05ab7df091b040b6fe9594d6), and release [v0.16.0](https://github.com/yassun4dev/serde_valid/tree/v0.16.0).
